// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.iapetus11.me.Data;

#nullable disable

namespace api.iapetus11.me.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220224153213_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.1.22076.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.iapetus11.me.Data.AppDbContext+Link", b =>
                {
                    b.Property<long>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LinkId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LinkId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("api.iapetus11.me.Data.AppDbContext+LinkHit", b =>
                {
                    b.Property<long>("LinkHitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LinkHitId"));

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("LinkHitAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LinkId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("LinkHitId");

                    b.HasIndex("LinkId");

                    b.ToTable("LinkHits");
                });

            modelBuilder.Entity("api.iapetus11.me.Data.AppDbContext+LinkHit", b =>
                {
                    b.HasOne("api.iapetus11.me.Data.AppDbContext+Link", "Link")
                        .WithMany()
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Link");
                });
#pragma warning restore 612, 618
        }
    }
}
