export const minecraftColors = {
  dark_red: { nice: "Dark Red", code: "4", hex: "AA0000" },
  red: { nice: "Red", code: "c", hex: "FF5555" },
  gold: { nice: "Gold", code: "6", hex: "FFAA00" },
  yellow: { nice: "Yellow", code: "e", hex: "FFFF55" },
  dark_green: { nice: "Dark Green", code: "2", hex: "00AA00" },
  green: { nice: "Green", code: "a", hex: "55FF55" },
  aqua: { nice: "Aqua", code: "b", hex: "55FFFF" },
  dark_aqua: { nice: "Dark Aqua", code: "3", hex: "00AAAA" },
  dark_blue: { nice: "Dark Blue", code: "1", hex: "0000AA" },
  blue: { nice: "Blue", code: "9", hex: "5555FF" },
  light_purple: { nice: "Light Purple", code: "d", hex: "FF55FF" },
  dark_purple: { nice: "Dark Purple", code: "5", hex: "AA00AA" },
  white: { nice: "White", code: "f", hex: "FFFFFF" },
  gray: { nice: "Gray", code: "7", hex: "AAAAAA" },
  dark_gray: { nice: "Dark Gray", code: "8", hex: "555555" },
  black: { nice: "Black", code: "0", hex: "000000" },
};

export const minecraftColorsCodes = {
  4: { nice: "Dark Red", name: "dark_red", hex: "AA0000" },
  c: { nice: "Red", name: "red", hex: "FF5555" },
  6: { nice: "Gold", name: "gold", hex: "FFAA00" },
  e: { nice: "Yellow", name: "yellow", hex: "FFFF55" },
  2: { nice: "Dark Green", name: "dark_green", hex: "00AA00" },
  a: { nice: "Green", name: "green", hex: "55FF55" },
  b: { nice: "Aqua", name: "aqua", hex: "55FFFF" },
  3: { nice: "Dark Aqua", name: "dark_aqua", hex: "00AAAA" },
  1: { nice: "Dark Blue", name: "dark_blue", hex: "0000AA" },
  9: { nice: "Blue", name: "blue", hex: "5555FF" },
  d: { nice: "Light Purple", name: "light_purple", hex: "FF55FF" },
  5: { nice: "Dark Purple", name: "dark_purple", hex: "AA00AA" },
  f: { nice: "White", name: "white", hex: "FFFFFF" },
  7: { nice: "Gray", name: "gray", hex: "AAAAAA" },
  8: { nice: "Dark Gray", name: "dark_gray", hex: "555555" },
  0: { nice: "Black", name: "black", hex: "000000" },
};
